# Task类详解

## 一.Task类总结

`asyncio.Task` 是 Python `asyncio` 模块中的一个类，表示一个协程任务。它用于在事件循环中并发执行协程，并提供了管理任务状态、等待任务完成和取消任务的方法。

他是作为一个python协程对象，和Future对象很像的这么一个对象，但不是线程安全的；他继承了Future所有的API，除了Future.set_result()和Future.set_Exception()；

使用高层API  asyncio.ccreate_task()创建任务，或者是使用低层API loop.create_task()或者是loop.ensure_future()创建任务对象；

相比于协程函数，任务时有状态的，可以使用Task.cancel()进行取消，这会触发CancelledError异常，使用cancelled()检查是否取消。

## 二.Task常用的函数

### 1.cancel

**结构：**

```python
task.cancel()
```

**作用：**

取消异步任务或协程的操作。取消任务是一种管理异步操作的方式，允许您中断正在进行的操作，以便更灵活地控制程序的行为。

使用他会出发CancelledError异常，所以需要取消的协程函数里面的代码最好在try-except语句块中进行，这样方便触发异常，打印相关信息。

Task.cancel()没有办法保证任务一定会取消，而Future.cancel()是可以保证任务一定取消的。

```python
import asyncio


async def cancel_me():
    print('cancel_me(): before sleep')
    try:
        await asyncio.sleep(3600)  # 模拟一个耗时任务
    except asyncio.CancelledError:
        print('cancel_me(): cancel sleep')
        raise
    finally:
        print('cancel_me(): after sleep')


async def main():
    # 通过协程创建一个任务，需要注意的是，在创建任务的时候，就会跳入到异步开始执行
    task = asyncio.create_task(cancel_me())
    # 等待一秒钟
    await asyncio.sleep(1)
    print('main函数休息完了')
    # 发出取消任务的请求
    task.cancel()
    try:
        await task  # 因为任务被取消，触发了异常
    except asyncio.CancelledError:
        print("main(): cancel_me is cancelled now")


asyncio.run(main())
```

运行过程分析：

首先run函数启动主函数入口main，在main中，因为第一句话就是调用异步函数cancel_me()函数，所以先打印出了第一句话；

然后进入cancel_me中的try语句，遇到await，暂停，这时候返回main中执行，但是有在main中遇到了await，也会暂停，但是由于main中只需要暂停1秒，而cancel_me中要暂停3600秒，所以等到main的暂停结束后，接着运行main，所以打印出第二句话；

接下来遇到取消任务的请求task.cancel()，然后继续执行main里面的try，又遇到了await，接着main进入暂停，接下来进入到cancel_me函数中，但是由于main中请求了取消任务，所以那个耗时3600秒的任务就不再执行了，直接触发了Cancelled_Error异常，打印出第三句话，接下来又raise一个异常信息；

接下来执行cancel_me的finally，打印出第四句话，此时cancel_me执行完毕，由于他抛出了一个异常，返回到主程序main中，触发异常，打印出第五句话。
### 2.done

当一个被包装得协程既没有触发异常、也没有被取消的时候，意味着它是done的，返回true。

**结构：**

```python
task.done()
```

**返回：**

如果任务已完成，`task.done()` 返回 `True`。

如果任务尚未完成，`task.done()` 返回 `False`。

**作用：**

```python
import asyncio


async def my_coroutine():
    await asyncio.sleep(1)
    print("Coroutine completed")


async def main():
    # 创建协程任务
    task = asyncio.create_task(my_coroutine())

    # 检查任务是否已完成
    if task.done():
        print("Task is already done")
    else:
        print("Task is not done yet")

    # 等待任务完成
    await task

    # 再次检查任务是否已完成
    if task.done():
        print("Task is now done")
    else:
        print("Task is not done yet")

asyncio.run(main())
```

### 3.result

**结构：**

```python
result = task.result()
```

**作用：**

**task.result()** 是Python `asyncio.Task` 类的一个方法，用于获取协程任务的执行结果。这个方法允许您获取任务的返回值

> 注意：
>
> task.result() 只能在任务已完成的情况下调用。如果任务尚未完成，调用此方法会引发 `asyncio.InvalidStateError` 异常。
>
> 如果任务在执行过程中引发了异常，调用 `task.result()` 会引发这个异常，而不是返回正常的结果。
>
> 因此，在访问任务的结果之前，通常需要检查任务的状态。

```python
import asyncio


async def my_coroutine():
    await asyncio.sleep(1)
    return "Coroutine completed"


async def main():
    # 创建协程任务
    task = asyncio.create_task(my_coroutine())

    # 等待任务完成
    await task

    # 获取任务的结果
    result = task.result()
    print("Task result:", result)


asyncio.run(main())
```

## 三.异步函数结果获取

### 1.直接通过result来获取

```python
import asyncio


async def hello1(a, b):
    print("Hello world 01 begin")
    await asyncio.sleep(3)  # 模拟耗时任务3秒
    print("Hello again 01 end")
    return a + b


coroutine = hello1(10, 5)
loop = asyncio.get_event_loop()  # 第一步：创建事件循环
task = asyncio.ensure_future(coroutine)  # 第二步:将多个协程函数包装成任务列表
loop.run_until_complete(task)  # 第三步：通过事件循环运行
print('-------------------------------------')
print(task.result())
loop.close()
```

### 2.通过定义回调函数来获取

```python
async def hello1(a, b):
    print("Hello world 01 begin")
    await asyncio.sleep(3)  # 模拟耗时任务3秒
    print("Hello again 01 end")
    return a + b


def callback(future):  # 定义的回调函数
    print(future.result())


loop = asyncio.get_event_loop()  # 第一步：创建事件循环
task = asyncio.ensure_future(hello1(10, 5))  # 第二步:将多个协程函数包装成任务
task.add_done_callback(callback)  # 并被任务绑定一个回调函数

loop.run_until_complete(task)  # 第三步：通过事件循环运行
loop.close()  # 第四步：关闭事件循环
```

> 注意：所谓的回调函数，就是指协程函数coroutine执行结束时候会调用回调函数。并通过参数future获取协程执行的结果。我们创建的task和回调里的future对象，实际上是同一个对象，因为task是future的子类。

